#!/bin/bash

# Put this file to /etc/bash_completion.d/pHmap_ENDL_()# needed because of Argbash --> m4_ignore([
### START OF CODE GENERATED BY Argbash v2.10.0 one line above ###
# Argbash is a bash code generator used to get arguments parsing right.
# Argbash is FREE SOFTWARE, see https://argbash.io for more info

_pHmap ()
{
	local cur prev opts base
	COMPREPLY=()
	cur="${COMP_WORDS[COMP_CWORD]}"
	prev="${COMP_WORDS[COMP_CWORD-1]}"
	all_long_opts="--pdb --ligand --set_view --level --rampcolors --surface_above --axis_update --digits --font --fontsize --weight --stretch --style --alignment --size --background --help --version --include "
	all_short_opts="-p -l -s -h -v -I "
	case "$prev" in
		--pdb|-p|--ligand|-l|--set_view|-s|--level|--rampcolors|--digits|--font|--fontsize|--weight|--stretch|--style|--alignment|--size|--background|--include|-I)
			COMPREPLY=( $(compgen -o bashdefault -o default -- "${cur}") )
			return 0
			;;
		*)
			case "$cur" in
				--*)
					COMPREPLY=( $(compgen -W "${all_long_opts}" -- "${cur}") )
					return 0
					;;
				-*)
					COMPREPLY=( $(compgen -W "${all_short_opts}" -- "${cur}") )
					return 0
					;;
				*)
					COMPREPLY=( $(compgen -o bashdefault -o default -- "${cur}") )
					return 0
					;;
			esac
	esac

}
complete -F _pHmap pHmap
### END OF CODE GENERATED BY Argbash (sortof) ### ])
