#!/bin/bash

# Put this file to /etc/bash_completion.d/pHmap_ENDL_()# needed because of Argbash --> m4_ignore([
### START OF CODE GENERATED BY Argbash v2.10.0 one line above ###
# Argbash is a bash code generator used to get arguments parsing right.
# Argbash is FREE SOFTWARE, see https://argbash.io for more info

_pHmap ()
{
	local cur prev opts base
	COMPREPLY=()
	cur="${COMP_WORDS[COMP_CWORD]}"
	prev="${COMP_WORDS[COMP_CWORD-1]}"
	all_long_opts="--ph_range --activity --ligand --set_view --digits --size --background --activityplot --activity_dataformat --activity_radius --activity_lollipop_circle_color --activity_lollipop_circle_stroke --activity_lollipopbar_color --activity_lollipop_errorbar_color --grid_linewidth --grid_place --grid_font_size --update_rendering --pymol_surface_mode --pymol_surface_solvent --pymol_surface_above_mode --pymol_ligand_representation --pymol_ramp --pymol_level --pymol_ramp_colors --update_axis --axis_font --axis_font_size --axis_font_weight --axis_font_stretch --axis_font_style --xalign --yalign --axisline --axisline_strokewidth --axisline_color --axisline_offset --help --version "
	all_short_opts="-r -a -l -s -h -v "
	case "$prev" in
		--ph_range|-r|--activity|-a|--ligand|-l|--set_view|-s|--digits|--size|--background|--activity_dataformat|--activity_radius|--activity_lollipop_circle_color|--activity_lollipop_circle_stroke|--activity_lollipopbar_color|--activity_lollipop_errorbar_color|--grid_linewidth|--grid_place|--grid_font_size|--pymol_surface_mode|--pymol_ligand_representation|--pymol_level|--pymol_ramp_colors|--axis_font|--axis_font_size|--axis_font_weight|--axis_font_stretch|--axis_font_style|--xalign|--yalign|--axisline_strokewidth|--axisline_color|--axisline_offset)
			COMPREPLY=( $(compgen -o bashdefault -o default -- "${cur}") )
			return 0
			;;
		*)
			case "$cur" in
				--*)
					COMPREPLY=( $(compgen -W "${all_long_opts}" -- "${cur}") )
					return 0
					;;
				-*)
					COMPREPLY=( $(compgen -W "${all_short_opts}" -- "${cur}") )
					return 0
					;;
				*)
					COMPREPLY=( $(compgen -o bashdefault -o default -- "${cur}") )
					return 0
					;;
			esac
	esac

}
complete -F _pHmap pHmap
### END OF CODE GENERATED BY Argbash (sortof) ### ])
